const pets = [
"Abyssal orphan",
"Baby mole",
"Callisto cub",
"Hellpuppy",
"Kalphite princess",
"Noon",
"Midnight",
"Olmlet",
"Pet chaos elemental",
"Pet dagannoth prime",
"Pet dagannoth supreme",
"Pet dagannoth rex",
"Pet dark core",
"Pet general graardor",
"Pet k'ril tsutsaroth",
"Pet kraken",
"Pet kree'arra",
"Pet smoke devil",
"Pet zilyana",
"Pet snakeling",
"Prince black dragon",
"Scorpia's offspring",
"Skotos",
"Tzrek-jad",
"Venenatis spiderling",
"Vet'ion jr.",
"Vorki"];

module.exports = {pets: pets};
